language: R
cache: packages
git:
  depth: false
branches:
  only:
  - master
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
r_packages:
    - blogdown
    - remotes
    - devtools
    - raster
    - rgdal
    - patchwork
before_script:
    - Rscript -e 'blogdown::install_hugo(version = "0.59.0")'
script:
    - Rscript -e 'blogdown::build_site()'
    - sh _build_and_merge.sh
    - touch public/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
